/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        ink: '#212121',
        'muted-slate': '#93939f',
        slate: '#75758a',
        hairline: '#d9d9dd',
        'border-light': '#e5e7eb',
        'soft-stone': '#eeece7',
        'pale-green': '#edfce9',
        'pale-blue': '#f1f5ff',
        coral: '#ff7759',
        'soft-coral': '#ffad9b',
        'action-blue': '#1863dc',
        'focus-blue': '#4c6ee6',
        'form-focus': '#9b60aa',
        'error-red': '#b30000',
        'near-black': '#17171c',
        'deep-green': '#003c33',
        'dark-navy': '#071829',
        surface: {
          DEFAULT: '#ffffff',
          dark: '#0f1117',
          card: '#ffffff',
          'card-dark': '#1a1d27',
        },
        glass: {
          light: 'rgba(255, 255, 255, 0.7)',
          dark: 'rgba(15, 17, 23, 0.8)',
        },
        indigo: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          950: '#1e1b4b',
        },
      },
      fontFamily: {
        display: ['Space Grotesk', 'Inter', 'ui-sans-serif', 'system-ui'],
        body: ['Inter', 'Arial', 'ui-sans-serif', 'system-ui'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular'],
      },
      fontSize: {
        'hero': ['96px', { lineHeight: '1', letterSpacing: '-0.02em' }],
        'hero-md': ['72px', { lineHeight: '1', letterSpacing: '-0.015em' }],
        'display-lg': ['60px', { lineHeight: '1', letterSpacing: '-0.012em' }],
        'display': ['48px', { lineHeight: '1.1', letterSpacing: '-0.01em' }],
        'heading-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.005em' }],
        'heading': ['24px', { lineHeight: '1.3' }],
        'body-lg': ['18px', { lineHeight: '1.4' }],
        'body': ['16px', { lineHeight: '1.5' }],
        'button': ['14px', { lineHeight: '1.71', fontWeight: '500' }],
        'caption': ['14px', { lineHeight: '1.4' }],
        'label': ['12px', { lineHeight: '1.4', letterSpacing: '0.02em' }],
      },
      borderRadius: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '22px',
        'xl': '30px',
        'pill': '32px',
        'full': '9999px',
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
        '30': '7.5rem',
      },
      backdropBlur: {
        'glass': '20px',
      },
      boxShadow: {
        'glass': '0 4px 30px rgba(0, 0, 0, 0.1)',
        'card': '0 1px 3px rgba(0, 0, 0, 0.06)',
        'elevated': '0 4px 20px rgba(0, 0, 0, 0.08)',
        'modal': '0 20px 60px rgba(0, 0, 0, 0.15)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'shimmer': 'shimmer 2s infinite linear',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
    },
  },
  plugins: [],
}
